worker_processes auto;
rtmp_auto_push on;
events {}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        # Application 'live' for ingest from stream.sh
        application live {
            live on;
            record off;

            # Pulling from local push and pushing to YouTube
            # This keeps the YouTube connection alive even if the source drops
            push rtmp://a.rtmp.youtube.com/live2/${YOUTUBE_STREAM_KEY};
        }
    }
}

# Optional: HTTP Stats
http {
    server {
        listen 8080;
        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        location /stat.xsl {
            root /www;
        }
    }
}
